language: go
go:
- 1.6
install:
- go get github.com/nexustix/boilerplate
- go get github.com/nxReplicator/nxReplicatorCommon
before_deploy:
- env GOOS=linux GOARCH=amd64 go build -o ${HOME}/dist/linux64/nxfusion github.com/nxReplicator/nxfusion
- env GOOS=windows GOARCH=amd64 go build -o ${HOME}/dist/windows64/nxfusion.exe github.com/nxReplicator/nxfusion
deploy:
  provider: releases
  api_key:
    secure: SKRIHdQpuaKA8JgLE75GvjFIq/ZzAfAFLVS53mSCxvgY/EGDnWlXU4ENrZpTw6DGPXQVgel+EqqqxUEHP5rh0/Pc8U9dcZ871qpIEFH9WQ7SpGJiB7pZDPUfVbO/o2GQD+LpMPJc+6yQnm2JfJ4B26E3Ow8904N6xfl9h4kVofm9dRC4WRFprSy96S7j59HY3sc5dpPdXolVS/svjKsWUE+/o3/j8qiziCCGj7MM31j9DkCbf6lBw0uzdu89qy2faSKK065csMW+1lvlFYDTjjPtT+DIvdliA9vMV70WZopOTJDgjjJnApndc9ei2Z8BkpHDXDggNrtvXQkP5hWFsaYQrxLqw6da6FMKqL7lNiPAa6jx8kIlu9V224VY0xpyhGPHeC1mlw/Hy5+uWK9mK1QdIWX2IWVlzsUofTG9P7Aj7Jsmt73WUPVyodV261dBrwPVCH1I6BE6eCAms2MeloHkCL6InxKsxbm61b9EbaS8N0V4Yd9btEbLTZ0a9hPKVfDEsjETIpV2WbIdppSqd1vSXMLQmzxCCwx7W+EenRyHcVM9wQLq9CG99IEVaAAYOserAAs44ZATnUqypGTJ4G4PUkUpLvHMLSYlZNqxB2bgPAdBB41vWyOynxUFV5pE8/Jn9FPj47bHTtJXdB0sebH8vSbh7f3vKCfxkSHZdF0=
  file:
    - "${HOME}/dist/windows64/nxfusion.exe"
    - "${HOME}/dist/linux64/nxfusion"
  skip_cleanup: true
  on:
    tags: true
